### ISSUE TITLE
Hi, when will you release your code ??

### ISSUE THREAD

**Issue by Johnson-yue** [Yuheng-Li/MixNMatch#1]

**Comment by Yuheng-Li** [comment]
Hi, the code will be released in next two weeks

**Comment by Johnson-yue** [comment]
thanks , I read your paper it is based on **fineGAN**, so the code is tensorflow??Would your supply pytorch version code？？

**Comment by Yuheng-Li** [comment]
it is based on pytorch

**Comment by Johnson-yue** [comment]
Great!!!  I am looking forward it

**Comment by Yuheng-Li** [comment]
Hi Johnson, the code and pre-trained models has been released
