### ISSUE TITLE
question about eval result and re-train result

### ISSUE THREAD

**Issue by Johnson-yue** [Yuheng-Li/MixNMatch#10]
Hi, thanks your helpping , I have finish re-train all stage.
There are 6 pictures for result:

## **Format**
| - | - |  - | - | 
|:---: | :---: | :---: | :---: |
|pose_file | background_file | shape_file | color_file |
|retrain_gen_feature_mode | `retrain_gen_code_mode` | pretrain_gen_code_mode |`pretrain_gen_feature_mode`|

## Pictures:
| pic name | pic |   
|:--- | :---: |
| pic_1 (pose-1, backgroud-1, shape-1, color-1) | ![pic_1](https://user-images.githubusercontent.com/10268274/74512102-7ce46480-4f42-11ea-872a-f80bc1e78037.png)|
| pic_2 (pose-2, backgroud-2, shape-2, color-2) | ![pic_2](https://user-images.githubusercontent.com/10268274/74512118-853c9f80-4f42-11ea-9a0f-8200a624b58a.png)|
| pic_3 (pose-3, backgroud-3, shape-3, color-3) | ![pic_3](https://user-images.githubusercontent.com/10268274/74512127-8a015380-4f42-11ea-9a36-7393d07e66ce.png) |
| pic_4 (pose-4, backgroud-4, shape-4, color-4) | ![pic_4](https://user-images.githubusercontent.com/10268274/74512135-8ec60780-4f42-11ea-81a5-8a46d240b2b1.png) |
| pic_5 (pose-5, backgroud-5, shape-5, color-5) | ![pic_5](https://user-images.githubusercontent.com/10268274/74512144-92f22500-4f42-11ea-888e-5cc8da1cad2c.png) |
| pic_6 (pose-6, backgroud-6, shape-6, color-6) | ![pic_6](https://user-images.githubusercontent.com/10268274/74512148-984f6f80-4f42-11ea-919a-f73c97e4972a.png) |

## My quesions:
 **Q1:** why object of pic_1 is out of picture in code mode ? such as both **_pic_1_**(retrain_gen_code_mode and pretrain_gen_code_mode ) ?

 **Q2:** my retrain model weight maybe failed in capture texture feature ? Did you have some experience for this ? the reason is different random seed or something else? such as **_all retrain_gen pictures_**

 **Q3:**  Nothing to be generated except background, [such as pic_5(`retrain_gen_code_mode`)], or bad backgroud [such as **_pic_6_**(`pretrain_gen_feature_mode`)]

**Comment by Yuheng-Li** [comment]
All these questions can be answered by the difference among models. Since this is adversarial training, models may even behave differently in different epoch. For example, a small shift of foreground generation, or a slightly different interpretation of texture and so on.

**Comment by Johnson-yue** [comment]
yes，you are right., but maybe there are some common phenomenon ， in all models？
like generate the part of objective （such as **Q1**）

It's just a hypothesis. You can be a feedback or nothing. Thank you for your reply
