### ISSUE TITLE
why not initialization the weight of BD_Networks? 

### ISSUE THREAD

**Issue by Johnson-yue** [Yuheng-Li/MixNMatch#11]
Hi, in [load_networks](https://github.com/Yuheng-Li/MixNMatch/blob/88f79721108286c3040e91a4b5ad88534dc2631b/code/train_first_stage.py#L69) functions  only three networks have been initialized : [netG](https://github.com/Yuheng-Li/MixNMatch/blob/88f79721108286c3040e91a4b5ad88534dc2631b/code/train_first_stage.py#L74), [netDs](https://github.com/Yuheng-Li/MixNMatch/blob/88f79721108286c3040e91a4b5ad88534dc2631b/code/train_first_stage.py#L79), [encoder](https://github.com/Yuheng-Li/MixNMatch/blob/88f79721108286c3040e91a4b5ad88534dc2631b/code/train_first_stage.py#L86)

but only BD not intialization ? **why** ? and this is your experiment performance ?

**Comment by Yuheng-Li** [comment]
You can initialize BD, it will have similar performance
