### ISSUE TITLE
Parameter details

### ISSUE THREAD

**Issue by sridhar21111976** [Yuheng-Li/MixNMatch#17]
Hi,

What is the significance of these parameters SUPER_CATEGORIES and FINE_GRAINED_CATEGORIES.

Also, Is there a minimum number of recommended Image count for training.  Do you have a Image preparation script to suit the model input for training.

**Comment by Yuheng-Li** [comment]
SUPER_CATEGORIES means the number of shapes you want the model to discover and group, whereas FINE_GRAINED_CATEGORIES means the number of texture. There are p and c code mentioned in the paper, please check the paper for more details.

We did not test what should be the minimum number of training images. It should depend on your data, but I recommend you should at least have a few thousand.  We do not have a preparation script as it is related to your own data. Make sure your preprocessed data follow the CUB data format before running
