### ISSUE TITLE
Bounding Box

### ISSUE THREAD

**Issue by avilatner** [Yuheng-Li/MixNMatch#19]
What implementation did you use to get the bounding box in that format? 
I can see that (x, y, w, h) is the pixel distance from the top and left, I just don't know of a library that uses that format.

**Comment by avilatner** [comment]
Is it YOLO format and https://github.com/tzutalin/labelImg ?

**Comment by Yuheng-Li** [comment]
Sorry, I do not fully understand your question.

But if you are asking where to get boxes, typically, they are provided (such as CUB http://www.vision.caltech.edu/visipedia/CUB-200-2011.html). If you do not have boxes for your own dataset, we suggest that you fire a pretrained detector. 

If you are asking how to get xywh format, then you can write your script to convert from whatever you have now to xywh format.

**Comment by avilatner** [comment]
Thanks, Yuheng-Li. You answered my question. I wasn't sure if it was (x,y,w,h) or (x1,y1,x2,y2) or another format and wanted to validate before I start training.
