### ISSUE TITLE
Codes and pre-trained weights

### ISSUE THREAD

**Issue by Gaurav-Veratech** [Yuheng-Li/MixNMatch#2]
Dear author, please upload the codes and pre-trained weights for the model.

**Comment by Uiuran** [comment]
Please!

**Comment by LiaoPan** [comment]
Please++

**Comment by imgugale** [comment]
Could you please upload the codes?

**Comment by utkarshojha** [comment]
Thanks a lot for the interest in the work. We’re still in the process of releasing the code, and expect the codes and pre trained models to be released sometime in January. Kindly check back then.

**Comment by ak9250** [comment]
@utkarshojha currently getting you need permission for the pretrained models google drive link

**Comment by Yuheng-Li** [comment]
The problem is fixed
