### ISSUE TITLE
where the trained modles?

### ISSUE THREAD

**Issue by orydatadudes** [Yuheng-Li/MixNMatch#20]
for my understanding to run eval.py and create new image (from 4 images ) i need the generator (G.pth) and  encoder (E.pth)
so after the first training stage i got folder with Model folder that contain the followings models : 
BD_0,DO_O,D1_0,D2_0,E_0,G_0
after training the second stage i have folder EX_0.pth
my general questions what s should i need to do next for making new image?
i need path for 4 images that is ok 
but i also need path to a folder with 3 pre trained models G.pth E.pth EX.pth - where are them?
do i need to take E_0,G_0 (from first training stage) and EX_0 (from second training stage) and put them together under the same folder and that folder is the models path?

few questions:
EX.pth that came from secound training stage is for feature mode?
for eval.py why do i need E.pth and EX.pth ?
how many epochs is needed (first and second stage) for getting the same resualts for birds datasets, the paper say nothing about that
thanks

**Comment by Yuheng-Li** [comment]
Yes, you need to put these three files together and rename them as G.pth, E.pth, EX.pth

for a few questions: 
Yes,
Because this is a conditional task 
600 and 400 epoches

**Comment by orydatadudes** [comment]
thank you for you answer
