### ISSUE TITLE
Large amount of data is needed?

### ISSUE THREAD

**Issue by hfz223322** [Yuheng-Li/MixNMatch#24]
I took the top 6 categories in CUB dataset(323 pictures) and only changed SUPER_CATEGORIES to 3 and FINE_GRAINED_CATEGORIES to 6 to run train_first_stage.py but got bad results. In my opinion, deep learning model will easily fit the dataset which has little amount of data, it semms that your model need large amount of data to train? Expect to get your reply, Thanks.

**Comment by Yuheng-Li** [comment]
yep, you probably need more data to train. 323 images are not enough in my experience

**Comment by hfz223322** [comment]
> yep, you probably need more data to train. 323 images are not enough in my experience

Thanks for your reply, I understand.
