### ISSUE TITLE
Converting a reference image according to a reference video

### ISSUE THREAD

**Issue by ak9250** [Yuheng-Li/MixNMatch#3]
is this keeping a video as pose images and then background, texture, and shape is the same image? Can you provide an example for Converting a reference image according to a reference video in eval.py?

**Comment by Yuheng-Li** [comment]
Here is how our eval.py works: you specify four images where they are pose(z), background(b), shape(p), and color(c) source images, and it will output a result image.
For example if you want to animate an image according to a reference video(like figure8 in our paper). Then for b,p,c reference image each time you just refer to that image, and take each frame from video as z reference image.
