### ISSUE TITLE
the Question about eval result!!

### ISSUE THREAD

**Issue by Johnson-yue** [Yuheng-Li/MixNMatch#4]
Hi, thank your sharing !!
It is very interesting, I have tested some birds picture with pre-trained model by using eval.py and I find some question 

I run the command line code:
`python eval.py --z pose/pose-2.png --b background/background-2.png --p shape/shape-2.png --c color/color-2.png --mode **_feature_** --models ../models/bird --out ./feature-2.png`
got **feature-2.png**
and I run the:
`python eval.py --z pose/pose-2.png --b background/background-2.png --p shape/shape-2.png --c color/color-2.png --mode **_code_** --models ../models/bird --out ./code-2.png`
got **code-2.png**  

the feature-2.png is the same as **/code/result/0001.png**
but when I check, **pose-2.png** , **background-2.png**, **shape-2.png** , **color-2.png**.
check image :
![mixmatch-demo](https://user-images.githubusercontent.com/10268274/74207118-329c8280-4cb9-11ea-8c79-eb53e91a28d6.png)

Conclusion:
## 1.the feature-2.png contain:
background of background-2.png, (checked )
shape of shape-2.png, (checked )
texture of color-2.png , (checked )
**but different pose from pose-2.png (failed)**

##  2.the code-2.png contain:
background of background-2.png, (checked )
_shape of shape-2.png, (maybe checked )_
texture of color-2.png , (checked )
**but different pose from pose-2.png (checked)**

My question is why it happened?

**Comment by Yuheng-Li** [comment]
Hi,

I think your concern lies in the purposes of two modes. The purpose of feature mode is to maintain exactly pixels level of shape+pose information from one reference image. As the document says, in this mode pose(z) source image will be ignored, and both shape and pose information are taken from the p reference image. 

That is why in your results, feature-2.png has the exact pixel-aligned shape with shape-2.png, while code-2.png has the shape of shape-2.png and pose of pose-2.png

**Comment by Johnson-yue** [comment]
thank your reply ， it is clearly。

I am still training first stage。I am using one RTX 2080 GPU and every iteration about 0.3s ， so the 600 epochs about 3 days， is right？？

How long does you train all stages finish？？ a week？

**Comment by Yuheng-Li** [comment]
For CUB the first stage training usually 500 epochs is fine. The second stage training is faster, usually take less than one day. The default total epochs for the second stage are 400, typically it converges around 100-200 epochs depending on datasets.  

we tested out model on birds other than from CUB, see FIg6 and Fig7 in the paper.
