### ISSUE TITLE
Wrong comment

### ISSUE THREAD

**Issue by Johnson-yue** [Yuheng-Li/MixNMatch#8]
background_stage network : this [line comment](https://github.com/Yuheng-Li/MixNMatch/blob/88f79721108286c3040e91a4b5ad88534dc2631b/code/model_train.py#L96)

because **ngf** = cfg.**GAN_GF_DIM** = **64** 
So   ` ngf*8 = 512` . 
The output feature of `self.fc is ngf*8*4*4 = 512 *4*4` ,  not `1024*4*4`
So this function **all** comment is wrong

**Comment by Yuheng-Li** [comment]
Thanks for pointing it out, we will update
