### ISSUE TITLE
why multiple 4 ??

### ISSUE THREAD

**Issue by Johnson-yue** [Yuheng-Li/MixNMatch#9]
why code_z  ***4** in [Encoder Network](https://github.com/Yuheng-Li/MixNMatch/blob/88f79721108286c3040e91a4b5ad88534dc2631b/code/model_train.py#L417) ???

**Comment by Yuheng-Li** [comment]
the real z is drawn from a Gaussian and the last activation is Tanh with range of -1 to 1, thus we choose multiplying 4 (as long as your final range can cover the most mass)

**Comment by Johnson-yue** [comment]
thank you  , I understand
